"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var superHeros = [];
// const superPowers: number[] = [];
var superPowers = [];
superHeros.push("spiderman");
superPowers.push(2);
var allUsers = [];
allUsers.push({ name: "Hello", isActive: true });
console.log(allUsers);
